services:
  _defaults:
    public: true

  prestashop.core.image.parser.image_tag_source_parser:
    class: 'PrestaShop\PrestaShop\Core\Image\Parser\ImageTagSourceParser'

  prestashop.core.image.file_deleter:
    class: 'PrestaShop\PrestaShop\Core\Image\Deleter\ImageFileDeleter'

  prestashop.core.image.avif_extension_checker:
    class: 'PrestaShop\PrestaShop\Core\Image\AvifExtensionChecker'
    public: true
